const $=id=>document.getElementById(id),brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}),mf=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}),df=new Intl.DateTimeFormat("pt-BR");
const sb=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY);let user=null,m=new Date(),D={transactions:[],accounts:[],goals:[],cards:[],trips:[],events:[],archive:[],claims:[],apartment:null};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])),money=s=>Number(String(s||"0").replace(/\./g,"").replace(",","."));
async function init(){bind();let{data:{session}}=await sb.auth.getSession();if(session)await enter(session.user);sb.auth.onAuthStateChange(async(_,s)=>{if(s&&!user)await enter(s.user)})}
function bind(){
 $("authForm").onsubmit=async e=>{e.preventDefault();let{error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});$("authMsg").textContent=error?error.message:""};
 $("signup").onclick=async()=>{let{error}=await sb.auth.signUp({email:$("email").value,password:$("password").value});$("authMsg").textContent=error?error.message:"Confira seu e-mail para confirmar a conta."};
 document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openModal(b.dataset.open,b));
 document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());
 $("prev").onclick=()=>{m.setMonth(m.getMonth()-1);render()};$("next").onclick=()=>{m.setMonth(m.getMonth()+1);render()};
 $("transactionForm").onsubmit=saveTransaction;$("apartmentForm").onsubmit=saveApartment;$("txHasRefund").onchange=()=>$("refundFields").classList.toggle("hidden",!$("txHasRefund").checked);$("deleteTx").onclick=deleteCurrentTransaction;$("simpleForm").onsubmit=saveSimple;
 $("theme").onclick=()=>{localStorage.setItem("joli-theme",document.body.classList.contains("dark")?"light":"dark");theme()};
 $("logout").onclick=()=>sb.auth.signOut().then(()=>location.reload());$("search").oninput=renderTransactions;$("moduleFilter").onchange=renderTransactions;$("typeFilter").onchange=renderTransactions;
 $("importHistory").onclick=importHistory;$("importHistorySettings").onclick=importHistory;$("csv").onclick=exportCSV;$("backup").onclick=backup;$("ask").onclick=ask;
 $("ofxFile").onchange=importOFX;$("archiveMonth").onchange=renderArchive;$("archiveSearch").oninput=renderArchive;$("archiveType").onchange=renderArchive;document.querySelectorAll("[data-tx]").forEach(b=>b.onclick=()=>setTxType(b.dataset.tx));theme();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")
}
async function enter(u){user=u;$("auth").classList.add("hidden");$("app").classList.add("logged");await load();render()}
async function load(){let[t,a,g,c,tr,e,ar,cl,ap]=await Promise.all([
 sb.from("transactions").select("*").eq("user_id",user.id).order("date",{ascending:false}),
 sb.from("accounts").select("*").eq("user_id",user.id),sb.from("goals").select("*").eq("user_id",user.id),
 sb.from("credit_cards").select("*").eq("user_id",user.id),sb.from("trips").select("*").eq("user_id",user.id),
 sb.from("story_events").select("*").eq("user_id",user.id).order("event_date",{ascending:false}),
 sb.from("spreadsheet_archive").select("*").eq("user_id",user.id).order("sheet_name").order("row_number"),
 sb.from("reimbursement_claims").select("*").eq("user_id",user.id),
 sb.from("apartments").select("*").eq("user_id",user.id).maybeSingle()]);
 D.transactions=(t.data||[]).map(x=>({...x,amount:+x.amount}));D.accounts=(a.data||[]).map(x=>({...x,balance:+x.balance}));
 D.goals=(g.data||[]).map(x=>({...x,target:+x.target,current_amount:+x.current_amount}));D.cards=(c.data||[]).map(x=>({...x,credit_limit:+x.credit_limit}));
 D.trips=(tr.data||[]).map(x=>({...x,budget:+x.budget}));D.events=(e.data||[]).map(x=>({...x,amount:+x.amount}));D.archive=(ar.data||[]).map(x=>({...x,vargem_amount:x.vargem_amount===null?null:+x.vargem_amount,botafogo_amount:x.botafogo_amount===null?null:+x.botafogo_amount,total_amount:x.total_amount===null?null:+x.total_amount}));D.claims=(cl.data||[]).map(x=>({...x,amount:+x.amount}));D.apartment=ap.data?Object.fromEntries(Object.entries(ap.data).map(([k,v])=>[k,["property_value","down_payment","financed_amount","outstanding_balance","monthly_installment"].includes(k)?+v:v])):null
}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));scrollTo(0,0);render()}
const sameMonth=(d,x=m)=>{let z=new Date(d+"T12:00:00");return z.getMonth()===x.getMonth()&&z.getFullYear()===x.getFullYear()},sum=(arr,type)=>arr.filter(x=>!type||x.type===type).reduce((a,x)=>a+x.amount,0);
function render(){let cur=D.transactions.filter(x=>sameMonth(x.date));let inc=sum(cur,"income"),exp=sum(cur,"expense"),bal=inc-exp;$("month").textContent=mf.format(m);$("income").textContent=brl.format(inc);$("expenses").textContent=brl.format(exp);$("balance").textContent=brl.format(bal);$("rate").textContent=inc?`${Math.round(bal/inc*100)}% de economia`:"Sem receitas registradas";
 let assets=D.accounts.reduce((a,x)=>a+(x.type==="debt"?-Math.abs(x.balance):x.balance),0);$("netWorth").textContent=brl.format(assets);$("assetsTotal").textContent=brl.format(assets);
 let fiv=D.transactions.filter(x=>x.module==="FIV"),fg=sum(fiv,"expense"),fr=sum(fiv,"income");$("fivNet").textContent=brl.format(fg-fr);$("fivGross").textContent=brl.format(fg);$("fivRefund").textContent=brl.format(fr);$("fivCost").textContent=brl.format(fg-fr);
 let gt=D.goals.reduce((a,x)=>a+x.target,0),gc=D.goals.reduce((a,x)=>a+x.current_amount,0);$("goalsPct").textContent=gt?`${Math.round(gc/gt*100)}%`:"0%";
 let imported=D.transactions.some(x=>x.source_key&&x.source_key.startsWith("planilha-"))&&D.archive.length>0;$("importBanner").classList.toggle("hidden",imported);$("importDescription").textContent=`${JOLI_HISTORICAL_DATA.stats.transaction_count} registros, incluindo a FIV.`;
 renderRecent();renderTransactions();donut(cur);renderAdvisor(cur);renderFIV(fiv);renderClaims();renderArchive();renderApartment();renderAccounts();renderGoals();renderCards();renderTrips();renderStory()
}
function refundLabel(s){return({requested:"Reembolso solicitado",partial:"Reembolso parcial",received:"Reembolso recebido",denied:"Reembolso negado"})[s]||"Reembolso"}
function txHtml(x){let badges="";if(x.issue_type==="duplicate_payment")badges+=`<span class="badge warn">Pagamento duplicado</span>`;if(x.refund_status)badges+=` <span class="badge refund">${refundLabel(x.refund_status)}${x.refund_provider?` · ${esc(x.refund_provider)}`:""}</span>`;let note=x.notes?`<small class="tx-note-preview">📝 ${esc(x.notes.length>90?x.notes.slice(0,90)+"…":x.notes)}</small>`:"";return `<article class="tx" onclick="editTransaction('${x.id}')"><div class="tx-icon">${x.module==="FIV"?"♡":x.module==="Apartamento"?"⌂":x.type==="income"?"↗":"↘"}</div><div><h4>${esc(x.description)}</h4><small>${esc(x.subcategory||x.category)} · ${df.format(new Date(x.date+"T12:00:00"))} · ${esc(x.person)}</small>${note}${badges}</div><div class="tx-value ${x.type}"><b>${x.type==="income"?"+":"−"} ${brl.format(x.amount)}</b><small>${x.status==="planned"?"Previsto":esc(x.module||"Geral")}</small></div></article>`}
function renderRecent(){$("recent").innerHTML=D.transactions.slice(0,6).map(txHtml).join("")||'<p class="muted">Nenhum lançamento.</p>'}
function renderTransactions(){if(!$("allTransactions"))return;let q=$("search").value.toLowerCase(),mod=$("moduleFilter").value,type=$("typeFilter").value,arr=D.transactions.filter(x=>(!q||`${x.description} ${x.category} ${x.subcategory} ${x.notes}`.toLowerCase().includes(q))&&(!mod||x.module===mod)&&(!type||x.type===type));$("allTransactions").innerHTML=arr.map(txHtml).join("")||'<p class="muted">Nenhum resultado.</p>'}
function donut(cur){let by={};cur.filter(x=>x.type==="expense").forEach(x=>by[x.category]=(by[x.category]||0)+x.amount);let rows=Object.entries(by).sort((a,b)=>b[1]-a[1]),total=rows.reduce((a,x)=>a+x[1],0),cv=$("donut"),ctx=cv.getContext("2d"),C=["#247052","#4FA47A","#8AC7A6","#E4A85E","#D66F78","#7094B8","#8C78B0"];ctx.clearRect(0,0,230,230);if(total){let s=-Math.PI/2;rows.forEach((r,i)=>{let a=r[1]/total*Math.PI*2;ctx.beginPath();ctx.arc(115,115,72,s,s+a);ctx.strokeStyle=C[i%C.length];ctx.lineWidth=28;ctx.stroke();s+=a});ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--ink");ctx.font="700 14px sans-serif";ctx.textAlign="center";ctx.fillText(brl.format(total),115,120)}$("legend").innerHTML=rows.slice(0,7).map((r,i)=>`<div class="legend-item"><span><i class="dot" style="background:${C[i%C.length]}"></i>${esc(r[0])}</span><b>${total?Math.round(r[1]/total*100):0}%</b></div>`).join("")||'<span class="muted">Sem despesas neste mês.</span>'}
function renderAdvisor(cur){let inc=sum(cur,"income"),exp=sum(cur,"expense"),by={};cur.filter(x=>x.type==="expense").forEach(x=>by[x.category]=(by[x.category]||0)+x.amount);let top=Object.entries(by).sort((a,b)=>b[1]-a[1])[0],p=[];if(!cur.length)p.push("Ainda não há lançamentos neste mês.");else{if(inc)p.push(`A economia do mês está em ${Math.round((inc-exp)/inc*100)}%.`);if(top)p.push(`${top[0]} é a maior categoria, com ${brl.format(top[1])}.`);let planned=cur.filter(x=>x.status==="planned").reduce((a,x)=>a+x.amount,0);if(planned)p.push(`Há ${brl.format(planned)} em valores previstos.`)}$("advisor").textContent=p.join(" ")}
function renderFIV(fiv){let ex=fiv.filter(x=>x.type==="expense"),by={};ex.forEach(x=>by[x.subcategory||x.category]=(by[x.subcategory||x.category]||0)+x.amount);let max=Math.max(...Object.values(by),1);$("fivBreakdown").innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(x=>`<div class="break-row"><div class="break-head"><span>${esc(x[0].replace("FIV · ",""))}</span><b>${brl.format(x[1])}</b></div><div class="bar"><div style="width:${x[1]/max*100}%"></div></div></div>`).join("");$("fivTimeline").innerHTML=ex.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="timeline-item"><h4>${esc(x.description)}</h4><small>${df.format(new Date(x.date+"T12:00:00"))} · ${brl.format(x.amount)} · ${esc(x.person)}</small>${x.notes?`<p>${esc(x.notes)}</p>`:""}</div>`).join("")}

function claimStatus(s){return({received:"Recebido",received_as_credit:"Crédito no cartão",approved_pending:"Aprovado, aguardando depósito",requested:"Solicitado",partial:"Parcial",denied:"Negado"})[s]||s||"Não informado"}
function renderClaims(){if(!$("claimList"))return;let total=D.claims.reduce((a,x)=>a+x.amount,0);$("claimList").innerHTML=(D.claims.map(x=>`<article class="tx"><div class="tx-icon">↩</div><div><h4>${esc(x.provider)}</h4><small>${claimStatus(x.status)}${x.received_date?` · ${df.format(new Date(x.received_date+"T12:00:00"))}`:""}</small>${x.notes?`<small class="tx-note-preview">📝 ${esc(x.notes)}</small>`:""}</div><div class="tx-value income"><b>${brl.format(x.amount)}</b></div></article>`).join("")||'<p class="muted">Nenhum reembolso detalhado.</p>')+`<div class="archive-total"><span>Total detalhado nas observações</span><b>${brl.format(total)}</b></div>`}
function archiveMoney(v){return v===null||v===undefined?"—":brl.format(v)}
function renderArchive(){if(!$("archiveList"))return;let select=$("archiveMonth");if(select.options.length===1){[...new Set(D.archive.map(x=>x.month_label))].forEach(v=>{let o=document.createElement("option");o.value=v;o.textContent=v;select.appendChild(o)})}let q=$("archiveSearch").value.toLowerCase(),mo=select.value,t=$("archiveType").value;let arr=D.archive.filter(x=>(!mo||x.month_label===mo)&&(!q||`${x.category} ${x.vargem_person} ${x.botafogo_person} ${x.notes} ${JSON.stringify(x.raw_row)}`.toLowerCase().includes(q)));if(t==="notes")arr=arr.filter(x=>x.notes);if(t==="pending")arr=arr.filter(x=>x.vargem_paid===false||x.botafogo_paid===false);if(t==="summary")arr=arr.filter(x=>/cartão|cartao|gastos lívia|gastos livia|gastos joão|gastos joao|total|compramos/i.test(x.category));let groups={};arr.forEach(x=>(groups[x.month_label]??=[]).push(x));$("archiveList").innerHTML=Object.entries(groups).map(([label,rows])=>`<article class="card archive-group"><div class="title"><div><span>PLANILHA ORIGINAL</span><h3>${esc(label)}</h3></div><b>${rows.length} linhas</b></div><div class="archive-scroll"><table><thead><tr><th>Categoria</th><th>Vargem Grande</th><th>Data/Pago/Quem</th><th>Botafogo</th><th>Data/Pago/Quem</th><th>Total</th><th>Observações</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.category||"—")}</b></td><td>${archiveMoney(x.vargem_amount)}</td><td>${esc(x.vargem_date_raw||"—")} · ${x.vargem_paid===null?"—":x.vargem_paid?"Pago":"Pendente"} · ${esc(x.vargem_person||"—")}</td><td>${archiveMoney(x.botafogo_amount)}</td><td>${esc(x.botafogo_date_raw||"—")} · ${x.botafogo_paid===null?"—":x.botafogo_paid?"Pago":"Pendente"} · ${esc(x.botafogo_person||"—")}</td><td>${archiveMoney(x.total_amount)}</td><td>${esc(x.notes||"—")}</td></tr>`).join("")}</tbody></table></div></article>`).join("")||'<p class="muted">Nenhuma linha encontrada.</p>'}
function renderApartment(){let a=D.apartment;if(!a){$("apartmentContent").innerHTML='<div class="card"><p>Configure o financiamento do apartamento. A entrada de R$ 65.500,00 já foi identificada na planilha.</p></div>'}else{let amort=Math.max(a.financed_amount-a.outstanding_balance,0),pct=a.financed_amount?Math.min(amort/a.financed_amount*100,100):0;$("apartmentContent").innerHTML=`<div class="apartment-card"><span class="kicker">PATRIMÔNIO IMOBILIÁRIO</span><h2>${esc(a.name)}</h2><div class="apt-grid"><div><span>Valor do imóvel</span><b>${brl.format(a.property_value)}</b></div><div><span>Entrada</span><b>${brl.format(a.down_payment)}</b></div><div><span>Saldo devedor</span><b>${brl.format(a.outstanding_balance)}</b></div><div><span>Parcela</span><b>${brl.format(a.monthly_installment)}</b></div></div><div class="progress"><div style="width:${pct}%"></div></div><small>${Math.round(pct)}% do financiamento amortizado, conforme saldo informado.</small></div>`}let tx=D.transactions.filter(x=>x.module==="Apartamento");$("apartmentTransactions").innerHTML=tx.map(txHtml).join("")||'<p class="muted">Nenhum gasto adicional registrado.</p>'}
function renderAccounts(){$("accountList").innerHTML=D.accounts.map(x=>`<article class="mini-card"><span class="kicker">${x.type==="debt"?"DÍVIDA":"PATRIMÔNIO"}</span><h3>${esc(x.name)}</h3><strong>${brl.format(x.balance)}</strong><small>${esc(x.owner||"JOLI")}</small><div class="item-actions"><button class="btn danger" onclick="removeRow('accounts','${x.id}')">Excluir</button></div></article>`).join("")||'<p class="muted">Adicione contas, investimentos, imóveis e dívidas.</p>'}
function renderGoals(){$("goalList").innerHTML=D.goals.map(x=>{let p=x.target?Math.min(x.current_amount/x.target*100,100):0;return `<article class="mini-card"><span class="kicker">META</span><h3>${esc(x.name)}</h3><strong>${brl.format(x.current_amount)}</strong><small>de ${brl.format(x.target)}</small><div class="progress"><div style="width:${p}%"></div></div><small>${Math.round(p)}% concluída</small><div class="item-actions"><button class="btn danger" onclick="removeRow('goals','${x.id}')">Excluir</button></div></article>`}).join("")||'<p class="muted">Crie metas para viagens, reserva ou apartamento.</p>'}
function renderCards(){$("cardList").innerHTML=D.cards.map(x=>`<article class="mini-card"><span class="kicker">CARTÃO</span><h3>${esc(x.name)}</h3><strong>${brl.format(x.credit_limit)}</strong><small>Fecha dia ${x.closing_day} · vence dia ${x.due_day}</small><div class="item-actions"><button class="btn danger" onclick="removeRow('credit_cards','${x.id}')">Excluir</button></div></article>`).join("")||'<p class="muted">Adicione os cartões da JOLI.</p>'}
function renderTrips(){$("tripList").innerHTML=D.trips.map(x=>{let spent=D.transactions.filter(t=>t.module==="Viagem"&&t.trip_id===x.id&&t.type==="expense").reduce((a,t)=>a+t.amount,0),p=x.budget?Math.min(spent/x.budget*100,100):0;return `<article class="mini-card"><span class="kicker">VIAGEM</span><h3>${esc(x.name)}</h3><strong>${brl.format(spent)}</strong><small>Orçamento: ${brl.format(x.budget)} · ${x.start_date?df.format(new Date(x.start_date+"T12:00:00")):""}</small><div class="progress"><div style="width:${p}%"></div></div></article>`}).join("")||'<div class="card"><p>Crie uma viagem e acompanhe orçamento e gastos. A viagem para Bruxelas pode ser cadastrada aqui.</p></div>'}
function renderStory(){$("storyList").innerHTML=D.events.map(x=>`<article class="story-event"><div class="story-icon">${esc(x.icon||"✦")}</div><div><span class="kicker">${df.format(new Date(x.event_date+"T12:00:00"))}</span><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p></div>${x.amount?`<strong>${brl.format(x.amount)}</strong>`:""}</article>`).join("")||'<p class="muted">Registre os grandes momentos de vocês.</p>'}
function setTxType(t){$("txType").value=t;document.querySelectorAll("[data-tx]").forEach(x=>x.classList.toggle("active",x.dataset.tx===t))}
function openModal(kind,b){if(kind==="transaction"){resetTransactionForm();setTxType(b?.dataset.type||"expense");$("txModule").value=b?.dataset.module||"Casa";$("txDate").value=new Date().toISOString().slice(0,10);$("transactionModal").showModal();return}if(kind==="apartment"){let a=D.apartment||{};$("aptName").value=a.name||"Apartamento Botafogo";$("aptValue").value=a.property_value||"";$("aptDown").value=a.down_payment||65500;$("aptFinanced").value=a.financed_amount||"";$("aptBalance").value=a.outstanding_balance||"";$("aptPayment").value=a.monthly_installment||"";$("aptTotal").value=a.total_installments||"";$("aptPaid").value=a.paid_installments||0;$("apartmentModal").showModal();return}let schemas={account:["Novo item de patrimônio",[["name","Nome","text"],["balance","Saldo/valor","number"],["type","Tipo","select","bank|Conta bancária,investment|Investimento,property|Imóvel ou bem,debt|Dívida"],["owner","Responsável","select","Lívia|Lívia,João Pedro|João Pedro,JOLI|JOLI"]]],goal:["Nova meta",[["name","Nome","text"],["target","Valor da meta","number"],["current_amount","Valor atual","number"]]],card:["Novo cartão",[["name","Nome","text"],["credit_limit","Limite","number"],["closing_day","Dia de fechamento","number"],["due_day","Dia de vencimento","number"],["owner","Responsável","select","Lívia|Lívia,João Pedro|João Pedro,JOLI|JOLI"]]],trip:["Nova viagem",[["name","Nome","text"],["destination","Destino","text"],["budget","Orçamento","number"],["start_date","Data de início","date"],["end_date","Data de término","date"]]],event:["Novo momento",[["title","Título","text"],["event_date","Data","date"],["description","Descrição","text"],["icon","Símbolo","text"],["amount","Valor relacionado","number"]]]};let s=schemas[kind];$("simpleTitle").textContent=s[0];$("simpleForm").dataset.kind=kind;$("simpleFields").innerHTML=s[1].map(f=>f[2]==="select"?`<label>${f[1]}<select name="${f[0]}">${f[3].split(",").map(o=>{let[v,l]=o.split("|");return`<option value="${v}">${l}</option>`}).join("")}</select></label>`:`<label>${f[1]}<input name="${f[0]}" type="${f[2]}" ${f[2]!=="text"?"":"required"}></label>`).join("");$("simpleModal").showModal()}
async function saveTransaction(e){e.preventDefault();let row={user_id:user.id,type:$("txType").value,amount:money($("txAmount").value),description:$("txDescription").value,category:$("txCategory").value,subcategory:$("txCategory").value,date:$("txDate").value,person:$("txPerson").value,payment:$("txPayment").value,status:$("txStatus").value,module:$("txModule").value,notes:$("txNotes").value,issue_type:$("txIssueType").value||null,refund_provider:$("txHasRefund").checked?$("txRefundProvider").value:null,refund_status:$("txHasRefund").checked?$("txRefundStatus").value:null,refund_amount:$("txHasRefund").checked?money($("txRefundAmount").value):0,refund_date:$("txHasRefund").checked?($("txRefundDate").value||null):null,installment_number:1,installment_total:1};let id=$("txId").value,res=id?await sb.from("transactions").update(row).eq("id",id).eq("user_id",user.id):await sb.from("transactions").insert(row);if(res.error)return alert(res.error.message);resetTransactionForm();$("transactionModal").close();await load();render()}
function resetTransactionForm(){$("transactionForm").reset();$("txId").value="";$("deleteTx").classList.add("hidden");$("txHasRefund").checked=false;$("refundFields").classList.add("hidden");setTxType("expense")}
function editTransaction(id){let x=D.transactions.find(t=>t.id===id);if(!x)return;resetTransactionForm();$("txId").value=x.id;setTxType(x.type);$("txAmount").value=String(x.amount).replace(".",",");$("txDescription").value=x.description||"";$("txCategory").value=x.category||"Outros";$("txModule").value=x.module||"Casa";$("txDate").value=x.date;$("txPerson").value=x.person||"JOLI";$("txPayment").value=x.payment||"Pix";$("txStatus").value=x.status||"paid";$("txNotes").value=x.notes||"";$("txIssueType").value=x.issue_type||"";let has=!!(x.refund_provider||x.refund_status||Number(x.refund_amount)>0||x.refund_date);$("txHasRefund").checked=has;$("refundFields").classList.toggle("hidden",!has);$("txRefundProvider").value=x.refund_provider||"";$("txRefundStatus").value=x.refund_status||"";$("txRefundAmount").value=x.refund_amount?String(x.refund_amount).replace(".",","):"";$("txRefundDate").value=x.refund_date||"";$("deleteTx").classList.remove("hidden");$("transactionModal").showModal()}
async function deleteCurrentTransaction(){let id=$("txId").value;if(!id||!confirm("Excluir este lançamento?"))return;let{error}=await sb.from("transactions").delete().eq("id",id).eq("user_id",user.id);if(error)return alert(error.message);$("transactionModal").close();await load();render()}
async function saveApartment(e){e.preventDefault();let row={user_id:user.id,name:$("aptName").value,property_value:money($("aptValue").value),down_payment:money($("aptDown").value),financed_amount:money($("aptFinanced").value),outstanding_balance:money($("aptBalance").value),monthly_installment:money($("aptPayment").value),total_installments:+$("aptTotal").value||null,paid_installments:+$("aptPaid").value||0};let{error}=await sb.from("apartments").upsert(row,{onConflict:"user_id"});if(error)return alert(error.message);$("apartmentModal").close();await load();render()}
async function saveSimple(e){e.preventDefault();let kind=e.target.dataset.kind,table={account:"accounts",goal:"goals",card:"credit_cards",trip:"trips",event:"story_events"}[kind],row={user_id:user.id};new FormData(e.target).forEach((v,k)=>{if(["balance","target","current_amount","credit_limit","budget","amount"].includes(k))row[k]=money(v);else if(["closing_day","due_day"].includes(k))row[k]=+v;else row[k]=v});if(kind==="event")row.module="Geral";let{error}=await sb.from(table).insert(row);if(error)return alert(error.message);$("simpleModal").close();await load();render()}
async function removeRow(table,id){if(!confirm("Excluir este registro?"))return;let{error}=await sb.from(table).delete().eq("id",id).eq("user_id",user.id);if(error)return alert(error.message);await load();render()}
async function importHistory(){if(!confirm("Sincronizar todo o conteúdo da planilha? A proteção contra duplicidade permite executar novamente sem repetir registros."))return;let tx=JOLI_HISTORICAL_DATA.transactions.map(x=>({...x,user_id:user.id})),ev=JOLI_HISTORICAL_DATA.story_events.map(x=>({...x,user_id:user.id})),ar=JOLI_HISTORICAL_DATA.archive_rows.map(x=>({...x,user_id:user.id})),cl=JOLI_HISTORICAL_DATA.reimbursement_claims.map(x=>({...x,user_id:user.id}));$("sync").textContent="● importando";for(let i=0;i<tx.length;i+=100){let{error}=await sb.from("transactions").upsert(tx.slice(i,i+100),{onConflict:"user_id,source_key"});if(error){alert(error.message);$("sync").textContent="● erro";return}}for(let i=0;i<ar.length;i+=100){let{error}=await sb.from("spreadsheet_archive").upsert(ar.slice(i,i+100),{onConflict:"user_id,source_key"});if(error){alert(error.message);$("sync").textContent="● erro";return}}let r1=await sb.from("story_events").upsert(ev,{onConflict:"user_id,source_key"});if(r1.error)return alert(r1.error.message);let r2=await sb.from("reimbursement_claims").upsert(cl,{onConflict:"user_id,source_key"});if(r2.error)return alert(r2.error.message);await load();render();$("sync").textContent="● online";alert(`Sincronização concluída: ${tx.length} lançamentos, ${ar.length} linhas originais e ${cl.length} reembolsos detalhados.`)}
function ask(){let q=$("question").value.toLowerCase(),arr=D.transactions;if(!q)return;let answer="";let filtered=arr;if(q.includes("fiv"))filtered=arr.filter(x=>x.module==="FIV");if(q.includes("apartamento"))filtered=arr.filter(x=>x.module==="Apartamento");if(q.includes("lívia")||q.includes("livia"))filtered=filtered.filter(x=>x.person==="Lívia");if(q.includes("joão")||q.includes("joao"))filtered=filtered.filter(x=>x.person==="João Pedro");if(q.includes("mês mais caro")||q.includes("mes mais caro")){let by={};arr.filter(x=>x.type==="expense").forEach(x=>{let k=x.date.slice(0,7);by[k]=(by[k]||0)+x.amount});let top=Object.entries(by).sort((a,b)=>b[1]-a[1])[0];answer=top?`O mês com maior volume de despesas foi ${mf.format(new Date(top[0]+"-15T12:00:00"))}, com ${brl.format(top[1])}.`:"Não há dados suficientes."}else{let ex=sum(filtered,"expense"),inc=sum(filtered,"income");answer=`Encontrei ${filtered.length} lançamentos. Despesas: ${brl.format(ex)}. Receitas e reembolsos: ${brl.format(inc)}. Resultado líquido: ${brl.format(ex-inc)}.`}$("answer").textContent=answer}
function exportCSV(){let rows=[["Data","Tipo","Módulo","Categoria","Descrição","Pessoa","Pagamento","Status","Valor"]];D.transactions.forEach(x=>rows.push([x.date,x.type,x.module,x.subcategory||x.category,x.description,x.person,x.payment,x.status,x.amount.toFixed(2).replace(".",",")]));download(new Blob(["\ufeff"+rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\n")],{type:"text/csv"}),"joli-lancamentos.csv")}
function backup(){download(new Blob([JSON.stringify(D,null,2)],{type:"application/json"}),"joli-backup.json")}function download(b,n){let a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=n;a.click();URL.revokeObjectURL(a.href)}
async function importOFX(e){let f=e.target.files[0];if(!f)return;let text=await f.text(),blocks=text.match(/<STMTTRN>[\s\S]*?<\/STMTTRN>/gi)||[],rows=blocks.map((b,i)=>{let get=t=>((b.match(new RegExp(`<${t}>([^<\\r\\n]+)`,"i"))||[])[1]||"").trim(),amt=+get("TRNAMT"),date=get("DTPOSTED").slice(0,8);return{user_id:user.id,source_key:`ofx-${get("FITID")||f.name+"-"+i}`,type:amt>=0?"income":"expense",amount:Math.abs(amt),description:get("MEMO")||get("NAME")||"Importado do OFX",category:amt>=0?"Receitas":"Outros",subcategory:"Importação bancária",date:`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}`,person:"JOLI",payment:"Conta bancária",status:"paid",module:"Geral",notes:`Arquivo ${f.name}`,installment_number:1,installment_total:1}});if(!rows.length)return alert("Não encontrei lançamentos nesse OFX.");let{error}=await sb.from("transactions").upsert(rows,{onConflict:"user_id,source_key"});if(error)return alert(error.message);await load();render();alert(`${rows.length} lançamentos importados do OFX.`)}
function theme(){let t=localStorage.getItem("joli-theme")||"light";document.body.classList.toggle("dark",t==="dark");$("theme").textContent=t==="dark"?"☀":"☾"}init();